# =============================================================================
# consumers.jl
#
# Checks the contract between the solvers and everything that reads them.
#
# The sweeps, calibration drivers, plot scripts and .jmd logs read solver output
# by name -- `meanAssets[i] = eq.statistics.meanAssets` -- and assign it into
# plain Float64 arrays. Nothing checks that at load time, so a field renamed or
# dropped during a refactor surfaces only when someone next runs a sweep, which
# may be weeks later and on a cluster. This script closes that gap: it reads the
# names the consumers actually use and asserts each one is still published.
#
# Published names come from verify/baseline/<dir>.txt, which is generated by
# running the solver, so the check is against what the code really emits rather
# than against a hand-kept list.
#
#   julia verify/consumers.jl            # check every directory
#   julia verify/consumers.jl hi hiinf   # or a subset
#
# Exits nonzero if any consumed name is missing, so it can gate a commit.
#
# Marek Kapicka, 2026
# =============================================================================

using Printf

const ROOT = normpath(joinpath(@__DIR__, ".."))
const DIRS = isempty(ARGS) ?
    ["hi", "hi_htm", "hiinf", "hiinf_htm", "hd", "hd_htm", "hdinf", "hdinf_htm"] : ARGS

# A consumer is anything in a solver directory that is not the solver itself.
# run_*, calibrate_*, sweep_*, plot_*, join_results and the .jmd logs all read
# equilibria; solve_* is the producer and is excluded.
function consumer_files(dir)
    files = String[]
    isdir(joinpath(ROOT, dir)) || return files
    for f in readdir(joinpath(ROOT, dir))
        (endswith(f, ".jl") || endswith(f, ".jmd")) || continue
        startswith(f, "solve_") && continue
        push!(files, joinpath(ROOT, dir, f))
    end
    return files
end

# `eq.statistics.meanAssets`, `eqHD.statisticsAllAges.medianAssets`, and the
# nested read `eq.statistics.unconditionalDistributions.assetMass` -- only the
# first component after the group is the contract, the rest belongs to whoever
# built that sub-tuple.
const STAT_RE = r"\beq[A-Za-z_0-9]*\.(statistics|statisticsAllAges)\.([A-Za-z_][A-Za-z0-9_]*)"
const TOP_RE  = r"\beq[A-Za-z_0-9]*\.([A-Za-z_][A-Za-z0-9_]*)"

function consumed(dir)
    # Keyed by group, not merged: a name read from `statistics` is only
    # satisfied by `statistics` publishing it. Merging the two groups would let
    # a name dropped from one pass on the strength of the other, which is
    # exactly the failure this script exists to catch.
    stats = Dict("statistics" => Set{String}(), "statisticsAllAges" => Set{String}())
    top = Set{String}()
    for f in consumer_files(dir)
        text = read(f, String)
        for m in eachmatch(STAT_RE, text)
            push!(stats[m.captures[1]], m.captures[2])
        end
        for m in eachmatch(TOP_RE, text)
            push!(top, m.captures[1])
        end
    end
    setdiff!(top, ["statistics", "statisticsAllAges"])
    return stats, top
end

# What the solver actually publishes, read off the golden-master capture.
function published(dir)
    path = joinpath(ROOT, "verify", "baseline", dir * ".txt")
    isfile(path) || return nothing
    stats = Dict("statistics" => Set{String}(), "statisticsAllAges" => Set{String}())
    top = Set{String}()
    for line in eachline(path)
        startswith(line, "#") && continue
        key = strip(first(split(line, " = ")))
        parts = split(key, ".")
        if parts[1] in ("statistics", "statisticsAllAges")
            length(parts) >= 2 && push!(stats[String(parts[1])], String(parts[2]))
        else
            push!(top, String(parts[1]))
        end
    end
    return stats, top
end

failures = 0
missing_baseline = String[]
println("Consumer contract: names read outside the solvers, against what the solvers publish.\n")
for dir in DIRS
    pub = published(dir)
    if pub === nothing
        push!(missing_baseline, dir)
        continue
    end
    pub_stats, pub_top = pub
    con_stats, con_top = consumed(dir)

    bad = String[]
    for g in ("statistics", "statisticsAllAges"), n in sort(collect(setdiff(con_stats[g], pub_stats[g])))
        push!(bad, g * "." * n)
    end
    n_consumed = length(con_stats["statistics"]) + length(con_stats["statisticsAllAges"])
    # A top-level field is only checked when the capture covers it; the capture
    # emits scalars and arrays, so fields holding a struct or a nested tuple of
    # arrays (parameters, solutions) are outside its reach and are reported,
    # not failed.
    unchecked = sort(collect(setdiff(con_top, pub_top)))

    status = isempty(bad) ? "ok" : "MISSING"
    @printf("  %-11s %2d statistics reads, %-7s", dir, n_consumed, status)
    if isempty(bad)
        println()
    else
        println("  -> ", join(bad, ", "))
        global failures += length(bad)
    end
    isempty(unchecked) ||
        println("              not covered by the capture (check by hand if these move): ",
                join(unchecked, ", "))
end

isempty(missing_baseline) ||
    println("\n  no baseline capture for: ", join(missing_baseline, ", "),
            "  (run ./verify/run.sh baseline ", join(missing_baseline, " "), ")")

println()
if failures == 0
    println("  PASS: every consumed statistics name is published by the solver it is read from.")
else
    println("  FAIL: ", failures, " consumed name(s) are no longer published.")
    exit(1)
end
